id: P006686
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23370
  title: རྫ་དཔལ་སྤྲུལ་ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོའི་གསུང་ཐོར་བུ།
  author: ''
  volumes:
    6c7108b2534d4dcdacc2fdd4d0b3dcad:
      image_group_id: I1552
      title: ''
      volume_number: 1
      total_pages: 610
      base_file: v001.txt
